# Production Configuration
# Use this for production ingestion

data_source:
  year: 2021
  month: 1
  base_url: "https://d37ci6vzurychx.cloudfront.net/trip-data"
  taxi_type: yellow

database:
  # Update with your production database credentials
  # If you run against the local Docker Compose stack instead of a remote
  # production database, use the internal service host:
  #   postgresql://root:root@pgdatabase:5432/ny_taxi
  connection_string: "postgresql://prod_user:prod_password@prod-postgres.example.com:5432/ny_taxi_prod"
  table_name: "yellow_tripdata"

ingestion:
  chunk_size: 500000       # Large for performance
  n_jobs: 1
  drop_existing: false     # Keep existing data
  if_exists: "append"      # Add to existing table

logging:
  level: "INFO"            # Normal logging
  file: "logs/production.log"
